### ISSUE TITLE
Add some commenting system

### ISSUE THREAD

**Issue by dandv** [tableflip/tableflip-blog#4]
My vote would be for Disqus, but at least have one. At the end of [this awesome post](https://blog.tableflip.io/large-meteor-projects-best-practices/) we see 

> Suggestions for improvements will be gratefully received.

...but there's no easy way to make said suggestions.

**Comment by olizilla** [comment]
Glad you like the post! I guess we'd prefer that people open issues on github rather than hosting our own comments system, as the spam to useful comment ratios tend to be pretty bad. It's on the todo list to better sign-post that.

We're migrating the blog from Ghost to jekyll, so that we can publish it as a static site to simplify the hosting and support a more decentralised future by peering the content on [`dat`](https://datproject.org/) and [`ipfs`](https://ipfs.io/)
